### ISSUE TITLE
IE11 don't open new tab

### ISSUE THREAD

**Issue by elhachimi** [lynndylanhurley/ng-token-auth#159] opened 2015-06-01 19:14 UTC
First thanks a lot for this awesome module.
All is working fine except that for IE11, i think $auth.authenticate don't open up a new tab it uses the same window which redirect to the api, then get stuck in the redirecting page, is there any workaround for  this ?

**Comment by lynndylanhurley** [comment] 2015-06-01 19:18
Hi, this is due to poor `postMessage` support in IE. This means that two tabs / windows can't communicate with each other in IE.

I can't remember I've tested this in IE 11, but I do know that it was still a problem in IE 10. I'll check against 11 ASAP.

**Comment by elhachimi** [comment] 2015-06-01 19:19
Thanks

**Comment by posixpascal** [comment] 2015-06-01 21:50
Maybe we can use a workaround for IE like falling back to localStorage for communication between tabs? Unfortunately I don't have an IE installation at the moment.

**Comment by lynndylanhurley** [comment] 2015-06-02 00:50
@posixpascal - the problem is that often times the client lives on a different domain than the API. I don't think it's possible to set `localStorage` or cookie values cross-domain without a bunch of hacks.

**Comment by elhachimi** [comment] 2015-06-02 09:17
i think this is causing the hard redirection https://github.com/lynndylanhurley/ng-token-auth/blob/master/dist/ng-token-auth.js#L549

**Comment by booleanbetrayal** [comment] 2015-07-29 19:17
Working on a new PR with @nbrustein to address deficiencies in the OAuth flow. We're adding support for `sameWindow` (new default), `newWindow`, and `inAppBrowser`. Going to close this ticket in anticipation of that PR addressing several of these issues, and would like to start with a blank slate once we do. Here's the commit with the anticipated changes - https://github.com/lynndylanhurley/ng-token-auth/commit/cc9927956f5b3a0b7853b864be06208130817014

**Closed by booleanbetrayal** 2015-07-29 19:17 UTC
